In [2]:
import numpy as np


In [3]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [4]:
b = np.array([1,2,3,4,5,6,7,8,9])
b[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
c = b.copy()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
d = b.view()
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
c = np.array([13,14,15])
d = np.concatenate((a,c))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
np.array_split(d,2)

[array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15])]

In [13]:
np.where(d==4)

(array([3], dtype=int32),)

In [14]:
np.where(d%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13], dtype=int32),)

In [16]:
c = np.array([1,3,5,2,4,9,6])
np.sort(c)

array([1, 2, 3, 4, 5, 6, 9])

In [22]:
c = np.array([[2,4,3,1,5],[5,4,1,3,2]])
np.sort(c)

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [23]:
c = np.array(['apple','orange','banana','mango'])
np.sort(c)

array(['apple', 'banana', 'mango', 'orange'], dtype='<U6')

In [26]:
np.random.randint(100)

55

In [27]:
np.random.rand(10)

array([0.25947571, 0.62964912, 0.77278942, 0.69266438, 0.44033462,
       0.88553759, 0.39521682, 0.96179463, 0.67807957, 0.3055264 ])

In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.ones(4)

array([1., 1., 1., 1.])